# Generated by Django 4.2.11 on 2024-03-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_registform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registform',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
