# Generated by Django 4.2.11 on 2024-03-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rform',
            old_name='img',
            new_name='Profile_Photo',
        ),
    ]
