# Generated by Django 4.2.11 on 2024-03-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_img_rform_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rform',
            old_name='Profile_Photo',
            new_name='Profile_photo',
        ),
    ]
