# Generated by Django 4.2.11 on 2024-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_profile_photo_rform_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rform',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
