# Generated by Django 4.2.11 on 2024-03-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_rform_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rform',
            old_name='num',
            new_name='number',
        ),
    ]
